export const ds = {
  container: { 
    background: "#0c0c0c", 
    minHeight: "100vh", 
    padding: "0 20px 220px", 
    color: "#fff", 
    position: "relative", 
    overflowX: 'hidden', 
    fontFamily: '-apple-system, sans-serif' 
  },
  navHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", height: "70px" },
  navLeft: { display: "flex", alignItems: "center", gap: "12px", cursor: 'pointer' },
  navTitle: { fontSize: "17px", fontWeight: "900" },
  backBtn: { fontSize: "22px", color: '#666' },
  navRight: { display: "flex", alignItems: "center", gap: "12px" },
  pointBadge: { background: '#1a1a1a', padding: '6px 14px', borderRadius: '20px', border: '1px solid #333', display: 'flex', gap: '6px', alignItems: 'center' },
  coinIcon: { fontSize: '14px' },
  headerPoint: { fontSize: "15px", fontWeight: "800", color: "#ffb347" },
  profileCircle: { width: "36px", height: "36px", borderRadius: "50%", overflow: "hidden", border: "1px solid #444" },
  profileImg: { width: "100%", height: "100%", objectFit: "cover" },

  liveTicker: { height: '34px', background: 'rgba(255, 179, 71, 0.05)', margin: '0 -20px 10px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  tickerText: { fontSize: '11px', color: '#ffb347', fontWeight: '600' },

  eventBanner: { 
    background: "linear-gradient(135deg, #ffdeeb 0%, #fbc2eb 100%)", 
    borderRadius: "28px", 
    padding: "25px", 
    border: '1px solid #ffb6c1', 
    textAlign: 'center', 
    position: 'relative', 
    overflow: 'hidden', 
    height: '190px', 
    display: 'flex', 
    alignItems: 'center', 
    justifyContent: 'center' 
  },
  radarContainer: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' },
  radarCircle: { position: 'absolute', borderRadius: '50%', border: '8px solid rgba(255, 255, 255, 0.6)' },
  bannerContent: { position: 'relative', zIndex: 10, width: '100%' },
  bannerTop: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' },
  liveBadge: { color: '#fff', fontSize: '10px', fontWeight: '900', padding: '2px 8px', borderRadius: '4px' },
  roundInfo: { fontSize: '12px', color: '#555', fontWeight: '700' },
  timeLeftNum: { fontSize: '52px', fontWeight: '900', margin: '5px 0', color: '#333', letterSpacing: '-1px' },
  lastResultBar: { background: 'rgba(255,255,255,0.6)', padding: '8px 15px', borderRadius: '12px', display: 'inline-flex', alignItems: 'center', gap: '10px', marginTop: '10px' },
  lastLabel: { fontSize: '11px', color: '#333', fontWeight: '600' },
  resTag: { fontSize: '12px', fontWeight: '800', color: '#000' },

  sectionLabel: { fontSize: "16px", fontWeight: "900", margin: "35px 0 15px", display: 'flex', alignItems: 'center', gap: '8px' },
  labelBar: { width: '4px', height: '16px', background: '#ffb347', borderRadius: '2px' },
  subLabel: { opacity: 0.4, marginLeft: '5px', fontWeight: '400', fontSize: '12px' },

  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" },
  itemCard: { 
    height: "145px", 
    borderRadius: "24px", 
    position: 'relative', 
    display: "flex", 
    flexDirection: 'column', 
    alignItems: "center", 
    justifyContent: "center", 
    cursor: 'pointer', 
    overflow: 'hidden',
    transition: 'all 0.2s ease'
  },
  multiplier: { position: 'absolute', top: 12, left: 15, fontSize: '11px', fontWeight: '900', color: 'rgba(255,255,255,0.3)' },
  statBadge: { position: 'absolute', top: 12, right: 12, fontSize: '10px', color: '#ffb347', fontWeight: 'bold', background: 'rgba(0,0,0,0.5)', padding: '2px 6px', borderRadius: '4px' },
  itemIcon: { fontSize: "44px", marginBottom: '8px' },
  itemInfoText: { textAlign: 'center' },
  itemName: { fontSize: "16px", fontWeight: "900", display: 'block' },
  itemDesc: { fontSize: '10px', color: '#777', marginTop: '2px' },
  checkBadge: { 
    position: 'absolute', 
    top: 12, 
    right: 12, 
    width: '22px', 
    height: '22px', 
    borderRadius: '50%', 
    display: 'flex', 
    alignItems: 'center', 
    justifyContent: 'center', 
    color: '#000', 
    fontSize: '12px', 
    fontWeight: '900', 
    zIndex: 2 
  },

  tabSection: { marginTop: '40px' },
  tabHeader: { display: 'flex', gap: '20px', borderBottom: '1px solid #222' },
  tabBtn: { background: 'none', border: 'none', padding: '15px 5px', fontSize: '14px', fontWeight: '800', cursor: 'pointer' },
  tabContent: { background: '#111', borderRadius: '20px', marginTop: '15px', border: '1px solid #222', overflow: 'hidden' },
  histItem: { padding: '15px 20px', borderBottom: '1px solid #222', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  histLeft: { display: 'flex', flexDirection: 'column', gap: '4px' },
  histRound: { fontSize: '14px', fontWeight: '800' },
  histDetail: { fontSize: '11px', color: '#555' },
  histDate: { fontSize: '11px', color: '#444' },
  histRight: { textAlign: 'right' },
  histStatusBadge: { display: 'inline-block', fontSize: '8px', fontWeight: '900', padding: '2px 5px', borderRadius: '4px', marginBottom: '4px', color: '#000' },
  histEarn: { fontSize: '15px', fontWeight: '900' },
  histWinIcons: { fontSize: '10px', color: '#666', marginTop: '2px' },
  totalWinIcons: { fontSize: '15px', fontWeight: '900' },
  emptyText: { padding: '40px', textAlign: 'center', color: '#444', fontSize: '13px' },
  moreBtn: { width: '100%', padding: '15px', background: 'none', border: 'none', color: '#ffb347', fontWeight: '700', fontSize: '12px', cursor: 'pointer' },

  bottomPanel: { 
    position: "fixed", 
    bottom: 20, 
    left: 15, 
    right: 15, 
    background: "#1c1c1e", 
    padding: "20px", 
    borderRadius: "30px", 
    border: "1px solid #333", 
    zIndex: 100, 
    boxShadow: '0 -10px 40px rgba(0,0,0,0.5)' 
  },
  panelTop: { display: 'flex', justifyContent: 'space-between', marginBottom: '15px', alignItems: 'center' },
  selectionText: { fontSize: '13px', color: '#888' },
  clearBtn: { background: 'none', border: 'none', color: '#ff3b30', fontSize: '13px', fontWeight: '700' },
  amountPresets: { display: 'flex', gap: '8px', marginBottom: '15px' },
  presetBtn: { flex: 1, background: '#2c2c2e', border: 'none', color: '#fff', padding: '10px', borderRadius: '12px', fontSize: '11px', fontWeight: '700' },
  betInputGroup: { display: 'flex', gap: '10px' },
  mainInput: { flex: 1, background: '#000', border: '1px solid #444', borderRadius: '16px', padding: '15px', color: '#fff', fontSize: '18px', fontWeight: '800' },
  finalBtn: { background: '#ffb347', color: '#000', border: 'none', padding: '0 25px', borderRadius: '16px', fontWeight: '900' },
  
  pendingContainer: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
  pendingInfo: { display: 'flex', flexDirection: 'column', gap: '4px' },
  pendingTitle: { fontSize: '15px', fontWeight: '900', color: '#ffb347' },
  pendingDetail: { fontSize: '12px', color: '#888' },
  cancelBtn: { background: '#ff3b30', color: '#fff', border: 'none', padding: '12px 20px', borderRadius: '16px', fontWeight: '900', fontSize: '13px' },

  modalOverlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.9)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '20px' },
  modalCard: { background: '#222', padding: '40px 30px', borderRadius: '35px', textAlign: 'center', width: '100%', maxWidth: '320px', border: '1px solid #333' },
  modalTitle: { fontSize: '20px', fontWeight: '900' },
  modalInfoBox: { background: '#161616', padding: '15px', borderRadius: '15px', margin: '20px 0', display: 'flex', justifyContent: 'space-around', fontSize: '12px', color: '#aaa' },
  modalAmount: { fontSize: '32px', fontWeight: '900', marginBottom: '25px' },
  modalCloseBtn: { width: '100%', background: '#fff', color: '#000', border: 'none', padding: '18px', borderRadius: '18px', fontWeight: '900', fontSize: '16px' }
};