export const myStyles = {
  container: { background: "#0f0f12", minHeight: "100vh", color: "#fff", paddingBottom: '80px' },
  loading: { height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#D4AF37', background: '#0f0f12' },
  topBar: { height: "65px", display: "flex", alignItems: "center", padding: "0 20px", background: '#0f0f12', borderBottom: '1px solid #1c1c21' },
  subHeader: { height: "65px", display: "flex", alignItems: "center", padding: "0 20px", background: '#1c1c21' },
  subTitle: { flex: 1, textAlign: 'center', fontWeight: '800', fontSize: '16px', color: '#D4AF37' },
  backBtn: { background: "none", border: "none", color: "#fff", fontSize: "22px", cursor: 'pointer' },
  topTitle: { flex: 1, textAlign: "center", fontSize: "14px", fontWeight: "900", color: "#fff", letterSpacing: '3px' },
  settingsIcon: { fontSize: "18px", cursor: 'pointer', color: '#444' },
  profileHeaderMain: { background: "linear-gradient(180deg, #1c1c21 0%, #0f0f12 100%)", padding: "40px 24px 40px" },
  profileInfoMain: { display: "flex", alignItems: "center", gap: "22px" },
  avatarWrapper: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' },
  avatarLarge: { width: "90px", height: "90px", borderRadius: "28px", background: "#2a2a2e", overflow: 'hidden', border: '2px solid #D4AF37' },
  imgFull: { width: '100%', height: '100%', objectFit: 'cover' },
  editBadgeOutside: { background: "linear-gradient(to right, #D4AF37, #F9E076)", color: "#000", border: "none", padding: "5px 12px", borderRadius: "8px", fontSize: "10px", fontWeight: "900" },
  userTextMain: { flex: 1, display: 'flex', flexDirection: 'column', gap: '5px' },
  userIdMain: { fontSize: "24px", fontWeight: "900", color: "#fff", display: 'flex', alignItems: 'center', gap: '8px' },
  vipBadge: { fontSize: '10px', color: '#000', padding: '2px 6px', borderRadius: '4px', fontWeight: '900' },
  userNoMain: { fontSize: "11px", color: "#444", fontWeight: '600' },
  tierContainer: { margin: '5px 0' },
  tierText: { fontSize: '10px', color: '#888', marginBottom: '4px' },
  tierBarOuter: { width: '100%', height: '4px', background: '#333', borderRadius: '2px', overflow: 'hidden' },
  tierBarInner: { height: '100%', transition: 'width 0.5s ease' },
  balanceCard: { margin: "-20px 20px 25px", background: "rgba(255,255,255,0.03)", backdropFilter: 'blur(15px)', borderRadius: "24px", display: "flex", alignItems:'center', padding: "30px 0", border: '1px solid rgba(212, 175, 55, 0.1)' },
  balanceItem: { flex: 1, textAlign: "center" },
  divider: { width: '1px', height: '35px', background: 'rgba(255,255,255,0.05)' },
  label: { fontSize: "11px", color: "#666", marginBottom: "8px", fontWeight: "700" },
  value: { fontSize: "22px", fontWeight: "900", color: "#fff" },
  menuList: { padding: "0 20px" },
  goldMenu: { display: "flex", justifyContent: "space-between", alignItems: 'center', padding: "22px 24px", background: 'rgba(212, 175, 55, 0.05)', borderRadius: '22px', marginBottom: '20px', border: '1px solid rgba(212, 175, 55, 0.2)', cursor: 'pointer' },
  goldMenuContent: { display: 'flex', alignItems: 'center', gap: '12px' },
  goldTag: { background: '#D4AF37', color: '#000', fontSize: '9px', fontWeight: '900', padding: '2px 6px', borderRadius: '4px' },
  goldMenuTitle: { color: '#D4AF37', fontWeight: '900', fontSize: '15px' },
  menuGroup: { background: 'rgba(255,255,255,0.02)', borderRadius: '24px', overflow: 'hidden' },
  menuItem: { display: "flex", justifyContent: "space-between", padding: "20px 24px", borderBottom: "1px solid rgba(255,255,255,0.02)", cursor: 'pointer' },
  menuTitle: { fontSize: "15px", fontWeight: "600", color: "#ccc" },
  arrow: { color: '#333', fontSize: '14px' },
  settingList: { padding: '20px' },
  settingItem: { background: '#1c1c21', padding: '22px', borderRadius: '20px', marginBottom: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  settingText: { fontWeight: '700', color: '#eee' },
  formArea: { padding: '30px 20px' },
  inputGroup: { marginBottom: '25px' },
  inputLabel: { display: 'block', color: '#444', fontSize: '12px', marginBottom: '10px', fontWeight: '800', paddingLeft: '5px' },
  inputDisabled: { width: '100%', background: '#151518', border: 'none', borderRadius: '16px', padding: '18px', color: '#333', fontSize: '14px', fontWeight: '700' },
  input: { width: '100%', background: '#1c1c21', border: '1px solid #2a2a2e', borderRadius: '16px', padding: '18px', color: '#fff', fontSize: '14px' },
  saveBtn: { width: '100%', padding: '18px', background: 'linear-gradient(to right, #D4AF37, #F9E076)', color: '#000', border: 'none', borderRadius: '18px', fontWeight: '900', marginTop: '15px' },
  avatarPicker: { position: 'fixed', bottom: 0, left: 0, right: 0, background: '#1c1c21', padding: '35px 25px 45px', borderTopLeftRadius: '35px', borderTopRightRadius: '35px', boxShadow: '0 -15px 40px rgba(0,0,0,0.5)', zIndex: 1000 },
  pickerHeader: { display:'flex', justifyContent:'space-between', marginBottom: 25, alignItems:'center' },
  randomBtn: { background: '#333', color: '#fff', border: 'none', padding: '5px 12px', borderRadius: '8px', fontSize: '12px', fontWeight: '800' },
  closeBtn: { background:'none', border:'none', color:'#444', fontSize:'30px' },
  charGrid: { display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '12px', marginBottom: '30px' },
  pickerItem: { aspectRatio: '1/1', borderRadius: '14px', background: '#0f0f12', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  uploadBtn: { width: '100%', padding: '16px', background: '#2a2a2e', color: '#fff', border: 'none', borderRadius: '16px', marginBottom: '12px', fontWeight: '800', fontSize: '14px' },
  applyBtn: { width: '100%', padding: '20px', background: 'linear-gradient(to right, #D4AF37, #F9E076)', color: '#000', border: 'none', borderRadius: '18px', fontWeight: '900', fontSize: '16px' },
  logoutBtnMain: { width: '100%', padding: '40px', background: 'transparent', color: '#333', border: 'none', fontWeight: '800', fontSize: '13px', letterSpacing: '2px' }
};